### Get Me
GET http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc3Nzc2OTMwMSwiZXhwIjoxNzc3ODU1NzAxfQ.4_X_4GZgrxMRHs9JlcP9N3sqHMZjwJAyB-NDMpm085k